### ISSUE TITLE
Server Bug 수정

### ISSUE THREAD

**Issue by DeveloperRyou** [DeveloperRyou/ft_irc#42]
Server 객체 위주로 발생하는 버그 찾고 수정

**Comment by DeveloperRyou** [comment]
인자로 포트번호와 비밀번호 바꿔 입력했을 때 작동 정의 필요

**Comment by DeveloperRyou** [comment]
- [x] 포트 사용 불가시 에러 처리 필요
- [x] 메세지에 CR제거 필요
- [x] argument split에 op 제거 필요

**Comment by DeveloperRyou** [comment]
- [x] 채널에 2명 접속 불가

**Comment by DeveloperRyou** [comment]
- [x] privmsg 전송시 segfault

**Comment by ssoyeong-lee** [comment]
# Parser
- [x] 파싱에서 `:` 존재 시 벡터에 빈 요소 생성되는 것 같음 -> 제거 필요
- [x] 빈 문장 무시 (reply 전송하지 않음)
- [x] 명령어만 전송되는 경우 argv에 명령어 들어감 -> `PASS` 전송 시 `argv[0] = PASS` 이다
- [x] Parser::mode() 에서 argv.size() == 0  으로 수정
- [x] Parser::invite()에서 argv.size() > 2 , < 2로 각각 수정
- [x] Parser::topic()에서 argv.size() ==  0으로 수정
 
## PASS
- [x] 재전송 시 `:*.freenode.net 462 nickname :You may not reregister` 전송 

## USER
- [x] `USER user 0 * real` hostname 설정 필요?
+ gethostbyname() 과 같은 관련 함수 서브젝트에 명시 -> 해야 할 듯...😥

- [x] 재전송 시 `:*.freenode.net 462 nickname :You may not reregister` 전송 
- [x] getClientNameList() -> chop와 일반 유저 반대로 리턴

## NICK
- [x] NICK: 닉네임 변경 성공 시 reply `soylee!~u@freenode-fef.4sl.2765s3.IP NICK :so`


# Client
- [x] client->send_to_Client () 인증 없어도 전송 가능하도록 처리
- [x] welcome 메시지 닉네임 변경 시마다 계속 전송되는 문제 수정

# Server

# Channel

## JOIN
- [x] join 성공 시 broadcast 는 되는데, getClientNameList() 메시지 전송 안됨
- [x] join 성공 시 클라이언트 목록 전송 후 ` :End of /NAMES list.` 전송

## PART

## INVITE
- [x] invite 시도 시 setfault

## KICK

## TOPIC

## PRIVMSG
- [x] limechat에서 PRIVMSG 전송 시 자신이 받는 문제 (cli->getNickname()에서 client->getNickname() 으로 변경)

## MODE
- [x] `MODE #channel` 전송 시 reply 수정
- [ ] `MODE #channel` 전송 시 limechat 인식 x

# ???
- [x] 채널 모든 클라이언트 나감 -> segfault?

**Comment by DeveloperRyou** [comment]
- [x] 첫 채널 생성시 Invite only 채널로 생성됨
- [x] invite 안되었는데 join 시도시 map 에 들어가고 있음, ChannelMode 포인터가 널이라 segfault 나는듯
- [x] 에러 메세지 라임챗에서 나타나지 않음
- [x] 같은 닉네임의 client 중복 생성 가능, 생성 이후 기능 undefined
- [x] input 시 딜레이있음
